project:
  type: website
  output-dir: "docs"

website:
  title: "Malsha Chamodi"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd 
    right: 
      - icon: github
        href: https://github.com/malsha1111
      - icon: linkedin
        href: https://linkedin.com/in/m-t-m-chamodi-5139a5369

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

